#!/bin/bash

echo "🚨 DÉPLOIEMENT URGENT - CORRECTION ERREUR LOGIN 500"
echo "================================================="

echo "📝 PROBLÈME À RÉSOUDRE:"
echo "- Erreur 500 lors du login en production"
echo "- Erreur PostgreSQL 'column ug.id does not exist' corrigée dans le code"
echo "- Redéploiement nécessaire pour appliquer les corrections"
echo ""

echo "🚀 COMMANDES DE DÉPLOIEMENT:"
echo ""
echo "1. Arrêter l'application actuelle:"
echo "   docker-compose down"
echo ""
echo "2. Nettoyer et reconstruire l'image avec les corrections:"
echo "   docker-compose build --no-cache logiflow-app"
echo ""
echo "3. Redémarrer l'application corrigée:"
echo "   docker-compose up -d"
echo ""
echo "4. Vérifier le déploiement:"
echo "   docker-compose logs -f logiflow-app | head -30"
echo ""

echo "🎯 QUE SURVEILLER DANS LES LOGS:"
echo "✅ 'Production Environment Configuration'"
echo "✅ '🔧 Creating users table with name column'"
echo "✅ '✅ CRITICAL: Name column confirmed present'"
echo "✅ '✅ CRITICAL: Default admin user created: admin/admin'"
echo "✅ '[express] serving on port'"
echo ""
echo "❌ Éviter ces erreurs:"
echo "❌ 'column ug.id does not exist'"
echo "❌ 'Cannot convert undefined or null to object'"
echo "❌ 'ERROR Response: 500'"
echo ""

echo "🔑 TEST DE CONNEXION:"
echo "1. Aller sur: http://logiflow.ffnancy.fr:3000"
echo "2. Utiliser: admin / admin"
echo "3. Doit fonctionner sans erreur 500"
echo ""

echo "💡 SI ÇA NE FONCTIONNE TOUJOURS PAS:"
echo "1. Vérifier les logs: docker-compose logs logiflow-app | tail -50"
echo "2. Vérifier la base: docker-compose exec logiflow-postgres psql -U logiflow_admin -d logiflow_db -c '\\dt'"
echo "3. Tester l'API: curl http://logiflow.ffnancy.fr:3000/api/health"
echo ""

echo "📊 CORRECTIONS APPLIQUÉES:"
echo "- Requêtes SQL user_groups sans référence à ug.id"
echo "- ID composite user_id + group_id"
echo "- Table user_groups avec PRIMARY KEY(user_id, group_id)"
echo "- Build esbuild validé : 285.8kb en 60ms"